text="THE IRON IS NOT MY ENEMY, BUT MY GREATEST ALLY, PUSHING ME TO SHATTER MY PERCEIVED LIMITS AND FORGE A STRONGER, MORE RESILIENT VERSION OF MYSELF WITH EVERY REP, SET, AND DAY I SHOW UP"
print(text.lower())
